spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3307/m2z-diagram?createDatabaseIfNotExist=true

eureka:
  instance:
    hostname: host.docker.internal
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka
